### ISSUE TITLE
Publish directory to include $workflow.profile

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/JASEN#130]
It would be nice to have the publish directory look something like this:
```
publishDir = "${params.outdir}/${workflow.profile}/${tool}"
```
Though this will be quite tough because `publishDir` is defined in the config and the `${workflow.profile}` can only be defined in the nextflow module i.e. after the pipeline has been executed. Thus, the publish directory might have to look like this:
```
publishDir = "${params.outdir}/${tool}/${workflow.profile}"
```

**Comment by LordRust** [comment]
outdir/profile/tool/ would have been nice, but outdir/tool/profile/ is messy. I think I would prefer outdir/tool/ only in that case even if that means more files in the same dirs. Since the data will be further processed into a database or a report the published files themselves will be more like an archive. Using the same dir for different profiles do have the additional complication that you need to be sure that there are no duplicate ID's across profiles, which I had not thought of before, but it is potentially a problem since I assume Nextflow will just overwrite files happily?

**Comment by ryanjameskennedy** [comment]
Alternatively, we could add a `--species` flag that is set as a default to "", and use the following publish directory:
```
 publishDir = "${params.outdir}/${params.species}/${tool}"
```

**Comment by ryanjameskennedy** [comment]
It has been brought to my attention that species is now mentioned three times (profile, config and csv). Seeing as we have to specify a profile when executing the run. It may not be necessary to mention the species in the csv.
