### ISSUE TITLE
Make sure correct resfinder version is pulled

### ISSUE THREAD

**Issue by sylvinite** [genomic-medicine-sweden/JASEN#221]
Getting reports that resfinder keeps getting downloaded with versions differing from the containter file.

Try using the command manually. Verify it. And see if it needs a tag flag instead.

**Comment by samuell** [comment]
Turns out:

- The version of ResFinder specified in the `RESFINDER_VERSION` variable in the singularity file was not installed, but instead the last available version on PyPI. Only the git checkout was done with the correct version.
- For older versions of ResFinder, there was an issue with misspelled "length", erroneously spelled "lenght" eg for the dictionary key "ref_seq_length". This is [fixed since 4.4.0](https://bitbucket.org/genomicepidemiology/resfinder/src/master/CHANGELOG.md).

PR on its way ...
