### ISSUE TITLE
Installation: All Singularity images retrievable without self-builds

### ISSUE THREAD

**Issue by Igor-Bazov** [genomic-medicine-sweden/jasen#62]
I istalled Singularity using Conda.
Then I get this error:

(jasen) [JASEN]$ cd container && sudo bash -i build_container.sh && cd ..
[sudo] password for xxx: 
Building tool chewbbaca to chewbbaca_2.8.5.sif
sudo: singularity: command not found
(jasen) [container]$ singularity version
3.8.6

Is it possible to install JASEN not being a sudo?

**Comment by ryanjameskennedy** [comment]
I'm not sure if one needs sudo authority to install JASEN but I am sure that you should not be installing Singularity using conda. Try having a look [here](https://apptainer.org/admin-docs/master/installation.html).

**Comment by ryanjameskennedy** [comment]
Singularity requires sudo to build the images required for the pipeline to run. Without Singularity and these respective images, this pipeline cannot be run. Thus, one needs sudo privileges to run JASEN. If all of the singularity images were stored in [galaxy project](https://depot.galaxyproject.org/singularity/) then you could download everything without having to build some of the images yourself. As it stands, there are 5 images that need to be built by the user and 12 that are downloaded in order to run JASEN. Our goal is to host these on galaxy project (or a similar platform) in the near future.

**Comment by LordRust** [comment]
The singularity you install via conda will kind of work, but will run everything in sandbox and will likely give you issues with owner rights. So here one needs to ask a sysadmin to install apptainer/singularity properly. With more modern linux kernels it is possible to build images without sudo using --fakeroot but I have not tested that since our installations are too old. But for the release versions we should look at getting the images hosted. Scilifelabs data office could maybe serve them for us?

**Comment by ryanjameskennedy** [comment]
We've discussed a plan and reckon it's a good idea to push the five singularity images to an account created using [koofr](https://koofr.eu/pricing/).

**Comment by mhkc** [comment]
This would also simplify automated tests for RRs and could aid in #99
