### ISSUE TITLE
User selected path for conda environment and prp?

### ISSUE THREAD

**Issue by ikarls** [genomic-medicine-sweden/JASEN#84]
Especially when running on a computer cluster, the user might want to control where the conda environment and prp are installed. Perhaps deploy_conda.sh could have a path flag?

**Comment by ryanjameskennedy** [comment]
`deploy_conda.sh` shouldn't install prp since prp is used via a singularity image so I will remove that! My bash skills are not good enough to create arguments/flags for such. Are you wanting to separate the location of your conda executables from your environment? I'm not quite sure as to why you would want to specify your conda environment path?

**Comment by ikarls** [comment]
For me the jasen conda environment was created in the home directory. In order to avoid filling up the home directory I ended up doing export `CONDA_ENVS_PATH=/path/to/none/home/dir` before creating the environment. So maybe it is more a tip for the installation than needed by the pipeline.

Good if prp is run in an image now, I had a dependency error when trying to install it.
