### ISSUE TITLE
Pipeline result processor (prp) removes chewbacca calls

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/JASEN#91]
If any of the following [calls](https://chewbbaca.readthedocs.io/en/latest/user/modules/AlleleCall.html#outputs) are found in the chewbacca output file, prp removes them, resulting in a loss of information. This is performed by a function called [parse_cgmlst_results](https://github.com/genomic-medicine-sweden/JASEN/blob/ff3ae36d9b7e89496b1503edf65acc2caa3e37dd/bin/pipeline_result_processor/prp/parse/typing.py#L30). Essentially, if the string from the `ERROR` list variable (`ERRORS = ["LNF", "PLOT3", "PLOT5", "NIPH", "NIPHEM", "ALM", "ASM"]`) is found in the chewBACCA output, then it is removed by the [replace_errors ](https://github.com/genomic-medicine-sweden/JASEN/blob/ff3ae36d9b7e89496b1503edf65acc2caa3e37dd/bin/pipeline_result_processor/prp/parse/typing.py#L47) function. I wonder if it would be worthwhile keeping said functions and just removing the [line ](https://github.com/genomic-medicine-sweden/JASEN/blob/ff3ae36d9b7e89496b1503edf65acc2caa3e37dd/bin/pipeline_result_processor/prp/cli.py#L105) that calls it.

**Comment by LordRust** [comment]
The only thing prp should do is to remove the **INF-** part of newly inferred alleles. This information is quite useless if you decide to update the database with newly found alleles since the second isolate to find the same new (inferred) allele, will not get the **INF-** part, and will just look like a regular allele. The other solution would be to treat the database a read-only and discard all the inferred alleles, which would be a worse alternative.
